# Generated by Django 5.0.2 on 2024-04-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElBuenSaborApp', '0002_adiciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adiciones',
            name='adiciones',
            field=models.CharField(max_length=50),
        ),
    ]
