# Generated by Django 5.0.2 on 2024-04-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElBuenSaborApp', '0003_alter_adiciones_adiciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adicion', models.CharField(max_length=50)),
                ('precio', models.CharField(max_length=10)),
                ('imagen', models.ImageField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'adicion',
                'verbose_name_plural': 'adiciones',
            },
        ),
        migrations.DeleteModel(
            name='Adiciones',
        ),
    ]
