# Generated by Django 5.0.2 on 2024-05-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElBuenSaborApp', '0007_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adicion',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
