# Generated by Django 5.0.2 on 2024-08-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElBuenSaborApp', '0009_venta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venta',
        ),
        migrations.AlterField(
            model_name='adicion',
            name='imagen',
            field=models.ImageField(upload_to='adiciones/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='productos/'),
        ),
    ]
