# Generated by Django 5.0.2 on 2024-06-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarritoApp', '0001_initial'),
        ('ElBuenSaborApp', '0008_alter_adicion_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapedido',
            name='adiciones',
            field=models.ManyToManyField(blank=True, to='ElBuenSaborApp.adicion'),
        ),
    ]
