# Generated by Django 5.0.2 on 2024-07-31 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarritoApp', '0002_lineapedido_adiciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineapedido',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='user',
        ),
    ]
